name: Run MATLAB Statements
on:
  workflow_dispatch:
  push:
jobs:
  my-job:
    name: Run MATLAB Statements
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Download dependencies
        run: |
          wget https://github.com/chebfun/chebfun/archive/f44234100d8af189d60e4bc533f5e98a0442a4c1.zip -O chebfun.zip
          unzip chebfun.zip
          wget https://www.chebfun.org/ATAP/atap-mfiles.zip
          unzip atap-mfiles.zip
          ls -R
      - name: Run statements
        uses: matlab-actions/run-command@v2
        with:
          command: publish('chap16.m','pdf')
